--- drivers/watchdog/Makefile
+++ drivers/watchdog/Makefile
@@ -25,6 +25,7 @@
 # ALPHA Architecture
 
 # ARM Architecture
+EXTRA_CFLAGS=-DDEBUG -DVERBOSE_DEBUG
 obj-$(CONFIG_AT91RM9200_WATCHDOG) += at91rm9200_wdt.o
 obj-$(CONFIG_AT91SAM9X_WATCHDOG) += at91sam9_wdt.o
 obj-$(CONFIG_OMAP_WATCHDOG) += omap_wdt.o
@@ -46,6 +47,7 @@
 obj-$(CONFIG_STMP3XXX_WATCHDOG) += stmp3xxx_wdt.o
 obj-$(CONFIG_NUC900_WATCHDOG) += nuc900_wdt.o
 obj-$(CONFIG_ADX_WATCHDOG) += adx_wdt.o
+obj-$(CONFIG_LPC313X_WATCHDOG) += wdt_lpc313x.o
 
 # AVR32 Architecture
 obj-$(CONFIG_AT32AP700X_WDT) += at32ap700x_wdt.o
