--- arch/arm/Makefile
+++ arch/arm/Makefile
@@ -172,6 +172,7 @@
 machine-$(CONFIG_ARCH_VERSATILE)	:= versatile
 machine-$(CONFIG_ARCH_W90X900)		:= w90x900
 machine-$(CONFIG_FOOTBRIDGE)		:= footbridge
+machine-$(CONFIG_ARCH_LPC313X)		:= lpc313x
 
 # Platform directory name.  This list is sorted alphanumerically
 # by CONFIG_* macro name.
