--- drivers/usb/gadget/Makefile
+++ drivers/usb/gadget/Makefile
@@ -22,6 +22,9 @@
 ifeq ($(CONFIG_ARCH_MXC),y)
 fsl_usb2_udc-objs		+= fsl_mx3_udc.o
 endif
+ifeq ($(ARCH_LPC313X),y)
+fsl_usb2_udc-objs		+= fsl_lpc_udc.o
+endif
 obj-$(CONFIG_USB_M66592)	+= m66592-udc.o
 obj-$(CONFIG_USB_R8A66597)	+= r8a66597-udc.o
 obj-$(CONFIG_USB_FSL_QE)	+= fsl_qe_udc.o
